settings:
  APP_DISPLAY_NAME: Uchar
  PRODUCTION_APP_NAME: Uchar
  APP_GROUP_IDENTIFIER: group.uz.uzinfocom.uchar
  BASE_BUNDLE_IDENTIFIER: uz.uzinfocom.uchar
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 86VMSY4FK5

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.uz.uzinfocom.uchar
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: uz.uzinfocom.uchar.app.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).uz.uzinfocom.uchar.app.keychain.shared"
